### ISSUE TITLE
Maximum body size limit of proxy

### ISSUE THREAD

**Issue by mrdanielm** [LocalCan/LocalCanApp#2]
## Description

Is there a way to customise the maximum body size of the proxy? I'm getting a 413 when trying to test an image upload

**Comment by Jaarson** [comment]
@mrdanielm What is the image size? Is the error coming from the LocalCan proxy or from your app?

**Comment by mrdanielm** [comment]
@Jaarson Image is just over 1MB. So to explain my setup my actual domain is on Cloudflare, if I create a custom domain pointing to my API and route traffic through that all is fine except when I attempt to upload an image and I get that error which appears to be at the proxy level because it never actually hits my API. 

I can successfully upload the same image both if testing locally (using localhost) and testing on a staging env again through CloudFlare.

I should also note if I create a CF based non-persistent URL in LocalCan, image upload works fine.

**Comment by Jaarson** [comment]
@mrdanielm thanks for waiting! Great news — LocalCan doesn't have any upload size limits anymore. Now, you can set and enforce any file size limits you need in your application.

Hope this helps and makes your development process smoother!

**Comment by mrdanielm** [comment]
Thank you for the prompt fix!
