### ISSUE TITLE
Localcan domains not working after switching network (wifi)

### ISSUE THREAD

**Issue by jigarmistry** [LocalCan/LocalCanApp#5]
## Description
When I change wifi network from one to another localcan domains stop working. I have to close and open again to make it work but that takes few seconds to work again.

## Steps to Reproduce

1. Open localcan app, connect Macbook to Wifi 1
2. Connect Macbook to Wifi 2
3. Localcan domains not working
4. Close and open Localcan app, it will work again after seconds.

## Current Behavior

It stop working after network wifi change.

## Expected Behavior

I would say it should work even if we change network wifi change.

## Environment

- App version: 2.3.4
- App architecture: arm64 (Apple silicon) 
- macOS version: macOS Sonoma  14.6.1

**Comment by Jaarson** [comment]
Thanks for pointing this out, @jigarmistry ! Haven't found a reliable way to detect Wi-Fi changes in Electron.js so far. I will focus on fixing this in the next release.

**Comment by jigarmistry** [comment]
Okay, Thanks

**Comment by Jaarson** [comment]
I've made the fix for it internally and will include it in the next release.

**Comment by jigarmistry** [comment]
Thanks for the fix. Waiting for a new release.

**Comment by Reizar** [comment]
+1 to have this released soon please. It's been causing us quite a few headaches.

**Comment by jigarmistry** [comment]
@Jaarson Any updates on it?

**Comment by Jaarson** [comment]
@jigarmistry I know it's taking a bit long – sorry about that. For some background, since LocalCan recently passed its 1-year mark, there are several early users whose "1 year of free updates" has expired, and they wouldn't be able to update if I released it now because there is no renewal flow in place yet. This is what I'm currently working on, and once it's done it will unblock the release 🤞

**Comment by jigarmistry** [comment]
Yeah but what about the users who recently onboarded so they need to wait for the fix for while then?

**Comment by jigarmistry** [comment]
Great. I will update and let you know here if that fixes it or not :)
