### ISSUE TITLE
Localcan stopped working after update to Macos 15.0 Sequoia

### ISSUE THREAD

**Issue by DennisNissen** [LocalCan/LocalCanApp#6]
## Description
After upgrading my Macos to 15.0 LocalCan is no longer able to connect the local domains. 

## Steps to Reproduce

- Upgrade to Macos 15
- Start LocalCan
## Current Behavior

.local Domains are not connected and show errors in the ui

## Expected Behavior

Domains are connected and no errors are shown in the UI. 
Error: "Network not supported or domain already in use"

## Environment

- App version: 2.3.4
- App architecture: arm64 (Apple silicon)
- macOS version: 15.0 (Sequoia)

![Bildschirmfoto von LocalCan am 25_09_2024, 16_08_28](https://github.com/user-attachments/assets/ee83f965-a481-4ed6-bab0-317b2b803073)

**Comment by Jaarson** [comment]
Hi Dennis. This is not a bug. Many people use LocalCan on Sequoia, including me, without issues.

A few questions:
1. Are you connected to WiFi?
2. Did you provide all permissions when you first opened LocalCan on Sonoma? (e.g. Settings -> Privacy & Security -> Local network)

**Comment by Jaarson** [comment]
If the issue still persist try these in this order:
1. Restarting your computer
2. Restart router
3. Reset DNS cache
    ```
    sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder; sudo killall mDNSResponderHelper; sudo dscacheutil -flushcache
    ```

I assume this is likely related to mDNS protocol

**Comment by DennisNissen** [comment]
Thank you for your prompt reply! That problem occured right after the update, so i was assuming that there's a connection. I already restarted my computer, restarted the router and reset the DNS-Cache, disconnected VPN's and networks, reattached them and checked permissions, but nothing seemed to help - - - UNTIL i "reinstalled" LocalCan (same version). I don't know if it was a combination of the actions i did. 

I am sorry to wasted your time and appreciate your help - Localcan is a great product that helped me a lot - keep going!

**Comment by Jaarson** [comment]
Awesome to hear you were able to resolve it!
Thanks and no worries, no time wasted 💪
