### ISSUE TITLE
Localcan stopped working since updated to Sequoia 15.2

### ISSUE THREAD

**Issue by vddgil** [LocalCan/LocalCanApp#9]
## Description
Everything is looking fine but domains are not responding
I tried everything in troubleshooting section, restarted my computer, removed and reinstalled Localcan (with complete reconfiguration), ...

## Steps to Reproduce

Update to Sequoia 15.2

## Current Behavior

Domains not reponding

## Expected Behavior

Domains should respond

## Environment

- App version: e.g LocalCan 2.3.7
- App architecture: arm64
- macOS version: Sequoia 15.2

**Comment by Jaarson** [comment]
Hey @vddgil, sorry to hear you are having issues.

Make sure to follow the steps in:
https://www.localcan.com/docs/troubleshooting/local-domains-are-slow

And specifically for Sequoia, make sure LocalCan has access to the local network in thr System Settings.
<img width="786" alt="SCR-20241216-nriv" src="https://github.com/user-attachments/assets/f4bcb375-78ea-4654-9f0c-b7da3fbd3915" />
